import type { Application } from "./types";

export const MOCK_APPLICATIONS: Application[] = [
  {
    company: "Acme Corp",
    role: "Senior Frontend Engineer",
    platform: "LinkedIn",
    language: "en",
    url: "https://linkedin.com/jobs/view/123456",
    current_status: "interview",
    applied_at: "2025-04-01T10:00:00Z",
    stages: [
      {
        id: 1,
        status: "applied",
        applied_at: "2025-04-01T10:00:00Z",
        email_body: "Thank you for applying to Acme Corp...",
        last_email_id: "msg_001",
      },
      {
        id: 2,
        status: "interview",
        applied_at: "2025-04-08T14:30:00Z",
        email_body: "We'd like to invite you for an interview...",
        last_email_id: "msg_002",
      },
    ],
  },
  {
    company: "Globex Inc",
    role: "Full Stack Developer",
    platform: "Indeed",
    language: "en",
    url: "https://indeed.com/jobs/view/789012",
    current_status: "ai_interview",
    applied_at: "2025-04-03T09:15:00Z",
    stages: [
      {
        id: 3,
        status: "applied",
        applied_at: "2025-04-03T09:15:00Z",
        email_body: "Your application has been received...",
        last_email_id: "msg_003",
      },
      {
        id: 4,
        status: "ai_interview",
        applied_at: "2025-04-10T11:00:00Z",
        email_body: "Please complete the following AI interview...",
        last_email_id: "msg_004",
      },
    ],
  },
  {
    company: "Initech",
    role: "React Developer",
    platform: "Glassdoor",
    language: "en",
    url: "https://glassdoor.com/jobs/view/345678",
    current_status: "applied",
    applied_at: "2025-04-10T16:45:00Z",
    stages: [
      {
        id: 5,
        status: "applied",
        applied_at: "2025-04-10T16:45:00Z",
        email_body: "We have received your application...",
        last_email_id: "msg_005",
      },
    ],
  },
  {
    company: "Umbrella Tech",
    role: "TypeScript Engineer",
    platform: "LinkedIn",
    language: "en",
    url: "https://linkedin.com/jobs/view/901234",
    current_status: "offer",
    applied_at: "2025-03-20T08:00:00Z",
    stages: [
      {
        id: 6,
        status: "applied",
        applied_at: "2025-03-20T08:00:00Z",
        email_body: "Application received for TypeScript Engineer...",
        last_email_id: "msg_006",
      },
      {
        id: 7,
        status: "interview",
        applied_at: "2025-03-27T13:00:00Z",
        email_body: "We would like to schedule a technical interview...",
        last_email_id: "msg_007",
      },
      {
        id: 8,
        status: "offer",
        applied_at: "2025-04-05T10:00:00Z",
        email_body: "We are pleased to extend an offer...",
        last_email_id: "msg_008",
      },
    ],
  },
  {
    company: "Stark Industries",
    role: "Software Engineer",
    platform: "Company Website",
    language: "en",
    url: "https://stark.com/careers/456",
    current_status: "rejected",
    applied_at: "2025-03-15T12:00:00Z",
    stages: [
      {
        id: 9,
        status: "applied",
        applied_at: "2025-03-15T12:00:00Z",
        email_body: "Thank you for your interest...",
        last_email_id: "msg_009",
      },
      {
        id: 10,
        status: "rejected",
        applied_at: "2025-03-25T09:00:00Z",
        email_body: "After careful consideration, we have decided to move forward with other candidates...",
        last_email_id: "msg_010",
      },
    ],
  },
  {
    company: "Wayne Enterprises",
    role: "Frontend Architect",
    platform: "AngelList",
    language: "en",
    url: "https://angel.co/jobs/567890",
    current_status: "applied",
    applied_at: "2025-04-12T11:30:00Z",
    stages: [
      {
        id: 11,
        status: "applied",
        applied_at: "2025-04-12T11:30:00Z",
        email_body: "Your application to Wayne Enterprises has been submitted...",
        last_email_id: "msg_011",
      },
    ],
  },
  {
    company: "Cyberdyne Systems",
    role: "UI Engineer",
    platform: "LinkedIn",
    language: "en",
    url: "https://linkedin.com/jobs/view/112233",
    current_status: "withdrawn",
    applied_at: "2025-03-10T14:00:00Z",
    stages: [
      {
        id: 12,
        status: "applied",
        applied_at: "2025-03-10T14:00:00Z",
        email_body: "Application received for UI Engineer position...",
        last_email_id: "msg_012",
      },
      {
        id: 13,
        status: "withdrawn",
        applied_at: "2025-03-18T10:00:00Z",
        email_body: "We have noted your withdrawal from the application process...",
        last_email_id: "msg_013",
      },
    ],
  },
];
